# Generated by Django 6.0.5 on 2026-05-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodSync', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='address',
        ),
        migrations.AddField(
            model_name='donor',
            name='health_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='hemoglobin',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
