# Generated by Django 6.0.5 on 2026-05-18 05:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodSync', '0002_remove_donor_address_donor_health_issues_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='email',
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospital_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='donor',
            name='hemoglobin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_donation_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='weight',
            field=models.FloatField(),
        ),
    ]
