# Generated by Django 6.0.5 on 2026-05-18 07:40

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodSync', '0003_remove_bloodrequest_request_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='contact_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='units_required',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='donor',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)]),
        ),
        migrations.AlterField(
            model_name='donor',
            name='hemoglobin',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(12.5)]),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='donor',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(45)]),
        ),
    ]
