# Generated by Django 6.0.5 on 2026-06-24 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodSync', '0004_bloodrequest_created_at_bloodrequest_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_question', models.CharField(choices=[('pet', "What is your first pet's name?"), ('school', 'What is your first school name?'), ('city', 'Which city were you born in?'), ('friend', 'Who is your childhood best friend?')], max_length=30)),
                ('security_answer', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
